VANAKKAM DA MAPLA
WINK "While Loop Example";
ANNAIKU KALAILA ix AARU MANI 1;
BABA COUNTING STARTS True
{
 WINK ix;
 ix PAYASAM SAPDUNGHA FRIENDS ix + 1;
 IPPO ix > 5
 {
  WINK "Loop out of bound";
  NIRUTHU UN NADAGATHA;
 }
 REPEATUH;
}
REPEATUH;
NANDRI VANNAKAM